Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        DDB_TABLE_NAME: bg-data
  Api:
    Auth:
      Authorizers: 
        BGCognito:
          AuthorizationScopes: 
            - email
          UserPoolArn: arn:aws:cognito-idp:us-east-2:319115845002:userpool/us-east-2_oYJIkyosz
      DefaultAuthorizer: BGCognito

Description: The AWS SAM template for the Bohemian Grove serverless backend.

Resources: 
  # User lambdas
  CreateUserFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BG-CreateUser
      PackageType: Image
      ImageUri: # TODO
      ImageConfig:
        EntryPoint:
          - ./CreateUserFn
        Command:
          - CreateUser.handler
      Description: Creates a single user in the DynamoDB table.
      Events: 
        Type: Api
        Properties: 
          Path: /user/{userName}
          Method: post
          RequestParameters:
            - method.request.path.userName


  GetUserFn: 
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BG-GetUser
      PackageType: Image
      ImageUri: # TODO
      Description: Gets a single user's information from the DynamoDB table.
      Events: 
        Type: Api
        Properties: 
          Path: /user/{userName}
          Method: get
          RequestParameters: 
            - method.request.path.userName


  UpdateUserFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BG-UpdateUser
      PackageType: Image
      ImageUri: # TODO
      Description: Updates a single user's information in the DynamoDB table.
      Events: 
        Type: Api
        Properties: 
          Path: /user/{userName}
          Method: put
          RequestParameters: 
            - method.request.path.userName


  DeleteUserFn:
  SearchUsersFn:

  # Post lambdas
  CreatePostFn:
  CreateCommentFn:
  GetPostFn:
  GetGlobalFeedFn:
  GetUserFeedFn:
  UpdatePostFn:
  DeletePostFn:
  DeleteCommentFn:

  # Image lambdas
  AddUserImgFn:
  ChangeUserImgFn: