version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BG-Serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cevoddeymacb"
s3_prefix = "BG-Serverless"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repository = "319115845002.dkr.ecr.us-east-2.amazonaws.com/bohemian-grove-serverless"
no_fail_on_empty_changeset = true